version: '2.1'

services:
  daxxer-api:
    container_name: 'daxxer-api'
    build: '.'
    ports:
      - '8000:8000'
    volumes:
      - './:/go/src/app'
    depends_on:
      mongo:
        condition: service_started
    networks:
      - daxxer-network

  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    networks:
      - daxxer-network

networks:
  daxxer-network:
    driver: bridge