version: '2.1'

services:
  daxxer-api:
    container_name: 'daxxer-api'
    build: '.'
    ports:
      - '8000:8000'
    volumes:
      - './:/go/src/app'
    depends_on:
      mongo:
        condition: service_started
    networks:
      - daxxer-network

  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    networks:
      - daxxer-network


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - daxxer-network

  skywalking-oap:
    image: apache/skywalking-oap-server:8.8.1
    container_name: skywalking-oap
    depends_on:
      elasticsearch:
        condition: service_healthy
    links:
      - elasticsearch
    ports:
      - "11800:11800"
      - "12800:12800"
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      JAVA_OPTS: "-Xms2048m -Xmx2048m"
    networks:
      - daxxer-network

  ui:
    image: apache/skywalking-ui:8.8.1
    container_name: ui
    depends_on:
      skywalking-oap:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    links:
      - skywalking-oap
    ports:
      - "8080:8080"
    environment:
      SW_OAP_ADDRESS: http://skywalking-oap:12800
    networks:
      - daxxer-network

networks:
  daxxer-network:
    driver: bridge